require: rubocop-rails

Style/Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

AllCops:
  Exclude:
    - config/**/*
    - db/migrate/*
    - db/schema.rb
    - bin/**/*