Style/Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false
AllCops:
  Exclude:
    - config/**/*
    - db/migrate/*
    - db/schema.rb
    - bin/**/*
    - app/controllers/graphql_controller.rb
